import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Bank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#1A1A1A]`}>
        <nav>
          <Navbar />
        </nav>
        {children}
        </body>
    </html>
  );
}
